Added handling of different param types
blinkops/blink-stackstorm-base pull request #7
Opened 2021-06-17 15:19 UTC by guyblink

2021-06-17 15:44 UTC, itsofirblink commented on implementation/stackstorm.go
> +		case "integer":
are you sure its only `integer`?

2021-06-17 15:44 UTC, itsofirblink commented on implementation/stackstorm.go
> +		switch definition.Type {
add more cases for `boolean` for example

2021-06-17 15:44 UTC, itsofirblink commented on implementation/stackstorm.go
> +
remove new line?

2021-06-17 15:44 UTC, itsofirblink commented on implementation/stackstorm.go
> +			}
Maybe try in line?

```go
if intValue, err := stconv.Atoi(value); err == nil {
    jsonMap[name] = intValue
} else {
    jsonMap[name] = value
}
```

2021-06-17 15:44 UTC, itsofirblink commented on implementation/stackstorm.go
> +			}
same here :)

2021-06-17 17:36 UTC, guyblink commented on implementation/stackstorm.go
> +		case "integer":
Fixed

2021-06-17 17:37 UTC, guyblink commented on implementation/stackstorm.go
> +		switch definition.Type {
Done

2021-06-17 17:37 UTC, guyblink commented on implementation/stackstorm.go
> +
I just like new lines before ifs for some reason but removed.

2021-06-17 17:37 UTC, guyblink commented on implementation/stackstorm.go
> +			}
Done

2021-06-17 17:37 UTC, guyblink commented on implementation/stackstorm.go
> +			}
Done

2021-06-19 10:37 UTC, danielsblinkops requested changes

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/implementation.go
> +		Values:      request.Parameters,
Values -> UserSuppliedValues

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/implementation.go
> +	}
new line

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +	Definitions map[string]StackStormParameter
you marshal the struct, so add `json:x` defenitions

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +func filterParameter(value string, definition StackStormParameter) bool {
Find a better name other than filterParameter.

Filter on what?
Why filter?
It does not actually filter but only returns whether is should be filetered

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +		definition := p.Definitions[name]
Check if the defenitions exists in the map plsz

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +		case "integer":
Move all the strings to constants so they can be easily aligned with the ones used in stackstorm

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +		case "array":
won't always be an array of strings

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +func populateDefaultValue(value *string, definition StackStormParameter) {
don't make value an output param, just return the new value

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +		if filterParameter(value, definition) {
i don't understand how u filter here on parameters with no value but that have default and in the next line you populateDefaultValue

2021-06-19 10:37 UTC, danielsblinkops commented on implementation/stackstorm.go
> +		if filterParameter(value, definition) {
there order before was first populate then filter i think

2021-06-20 08:41 UTC, guyblink commented on implementation/stackstorm.go
> +		if filterParameter(value, definition) {
The order was the same before but also doesn't matter. I specifically kept these functions independent to prevent us from relying on the order. They both check the default value. If it doesn't exist and the current value is empty, we may filter.

2021-06-20 08:41 UTC, guyblink commented on implementation/stackstorm.go
> +		definition := p.Definitions[name]
Done

2021-06-20 08:42 UTC, guyblink commented on implementation/stackstorm.go
> +	Definitions map[string]StackStormParameter
I only marshal the simple map[string]interface, not the struct.

jsonMap := map[string]interface{}{}

2021-06-20 08:42 UTC, guyblink commented on implementation/implementation.go
> +	}
Done

2021-06-20 08:42 UTC, guyblink commented on implementation/implementation.go
> +		Values:      request.Parameters,
Done

2021-06-20 08:44 UTC, guyblink commented on implementation/stackstorm.go
> +		case "array":
changed to []interface{}

2021-06-20 08:46 UTC, guyblink commented on implementation/stackstorm.go
> +func filterParameter(value string, definition StackStormParameter) bool {
shouldFilterEmptyValue

2021-06-20 08:49 UTC, guyblink commented on implementation/stackstorm.go
> +func populateDefaultValue(value *string, definition StackStormParameter) {
Done

2021-06-20 08:52 UTC, guyblink commented on implementation/stackstorm.go
> +		case "integer":
Done

2021-06-20 08:59 UTC, danielsblinkops requested changes

2021-06-20 08:59 UTC, danielsblinkops commented on implementation/stackstorm.go
> +	if value == "" && definition.Default != "" {
Use getDefaultValue in this function to prevent code dup

2021-06-20 09:27 UTC, guyblink commented on implementation/stackstorm.go
> +	if value == "" && definition.Default != "" {
Done

2021-06-21 20:39 UTC, merged